- name: append available custom variables to default variables
  set_fact:
    shorewall_zones: "{{ shorewall_zones_default + shorewall_zones_custom }}"
    shorewall_interfaces: "{{ shorewall_interfaces_default + shorewall_interfaces_custom }}"
    shorewall_snat: "{{ shorewall_snat_default + shorewall_snat_custom }}"
    shorewall_tunnels: "{{ shorewall_tunnels_default + shorewall_tunnels_custom }}"
    # custom policies have to be loaded before final default policy to reject all
    shorewall_policies: "{{ shorewall_policies_custom + shorewall_policies_default }}"

- name: lookup all shorewall_rule_templates and combine into shorewall_rule_templates_list
  set_fact:
    shorewall_rule_templates_list: "{{ shorewall_rule_templates_list + lookup('vars', 'shorewall_rule_template_' + shorewall_rule_template) }}"
  with_items: "{{ shorewall_rule_templates }}"
  loop_control:
    loop_var: shorewall_rule_template

- name: combine shorewall_default_rules + shorewall_rule_templates_list + shorewall_rules_custom
  set_fact:
    shorewall_rules:
      - section: NEW
        rules: "{{ shorewall_rules_default + shorewall_rule_templates_list + shorewall_rules_custom }}"



- name: install shorewall
  apt:
    name: shorewall
    state: present

- name: template /etc/default/shorewall
  template:
    src: templates/etc/default/shorewall.j2
    dest: /etc/default/shorewall
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall

- name: template shorewall config files
  template:
    src: "templates/etc/shorewall/{{ shorewall_config_file }}.j2"
    dest: "/etc/shorewall/{{ shorewall_config_file }}"
    owner: root
    group: root
    mode: 0640
  with_items:
    - shorewall.conf
    - zones
    - interfaces
    - policy
    - snat
    - tunnels
    - rules
  loop_control:
    loop_var: shorewall_config_file
  notify: restart shorewall
