# /etc/shorewall/shorewall.conf
shorewall_conf_startup_enabled: 'Yes'  # [Yes|No]
shorewall_conf_accounting: 'No'  # [Yes|No]
shorewall_conf_ip_forwarding: 'Off' # [On|Off|Keep]
shorewall_conf_logformat: 'shorewall:%s:%s:'  # ["formattemplate"]
shorewall_conf_logfile: '/var/log/syslog'  # [pathname] - Default is /var/log/messages
shorewall_conf_logtagonly: 'No'  # [Yes|No]
shorewall_conf_log_martians: 'Yes' # [Yes|No|Keep]
shorewall_conf_log_backend: ''
shorewall_conf_docker: 'No'
shorewall_conf_log_verbosity: '2'  # [-1=disabled|0=Silent|1=Major|2=All]
shorewall_conf_multicast: 'No'  # [Yes|No]
shorewall_conf_startup_log: '/var/log/shorewall-init.log'  # [pathname]
shorewall_conf_verbosity: '2'  # [0=Silent|1=Major|2=All]
shorewall_conf_disable_ipv6: 'No'
