- name: Converge
  hosts: all
  become: True
  roles:
    - role: role-shorewall
  vars:

    # inventory/host or group_vars
    nic_pub: enp0s3
    nic_pub_ip: 10.0.0.5
    nic_wg_mesh_ip: 172.16.0.43
    dns_servers_hosting_provider:
      - 8.8.4.4
      - 8.8.8.8
    ntp_servers_hosting_provider:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org
      - 3.pool.ntp.org
    smtp_servers:
      - smtp.gmail.com
    hkp_servers:
      - keyserver.ubuntu.com


    # role-shorewall

    # shorewall.conf
    # shorewall_conf_startup_enabled: "No"
    shorewall_conf_ip_forwarding: "On"
    shorewall6_conf_ip_forwarding: "On"

    # nics and ips
    shorewall_nic_pub: "{{ nic_pub }}"
    shorewall_nic_pub_ip: "{{ nic_pub_ip }}"
    shorewall_dns_servers_hosting_provider: "{{ dns_servers_hosting_provider }}"
    shorewall_ntp_servers_hosting_provider: "{{ ntp_servers_hosting_provider }}"
    shorewall_smtp_servers: "{{ smtp_servers }}"
    shorewall_hkp_servers: "{{ hkp_servers }}"

    # # utility servers public IPs
    # shorewall_util_pub_ip_gateway_1: "{{ hostvars['cus-utility-prod-gateway-1.cus.pm']['nic_pub_ip'] }}"
    # shorewall_util_pub_ip_gateway_2: "{{ hostvars['cus-utility-prod-gateway-2.cus.pm']['nic_pub_ip'] }}"
    # shorewall_util_pub_ip_backup_1: "{{ hostvars['cus-utility-prod-backup-1.cus.pm']['nic_pub_ip'] }}"
    # shorewall_util_pub_ip_monitoring_1: "{{ hostvars['cus-utility-prod-monitoring-1.cus.pm']['nic_pub_ip'] }}"
    # shorewall_util_pub_ip_log_1: "{{ hostvars['cus-utility-prod-log-1.cus.pm']['nic_pub_ip'] }}"
    # shorewall_util_pub_ip_git_1: "{{ hostvars['cus-utility-prod-git-1.cus.pm']['nic_pub_ip'] }}"
    # shorewall_util_pub_ip_gitci_1: "{{ hostvars['cus-utility-prod-gitci-1.cus.pm']['nic_pub_ip'] }}"
    # # utility servers wireguard mesh IPs
    # shorewall_util_wg_mesh_ip_gateway_1: "{{ hostvars['cus-utility-prod-gateway-1.cus.pm']['nic_wg_mesh_ip'] }}"
    # shorewall_util_wg_mesh_ip_gateway_2: "{{ hostvars['cus-utility-prod-gateway-1.cus.pm']['nic_wg_mesh_ip'] }}"
    # shorewall_util_wg_mesh_ip_backup_1: "{{ hostvars['cus-utility-prod-backup-1.cus.pm']['nic_wg_mesh_ip'] }}"
    # shorewall_util_wg_mesh_ip_monitoring_1: "{{ hostvars['cus-utility-prod-monitoring-1.cus.pm']['nic_wg_mesh_ip'] }}"
    # shorewall_util_wg_mesh_ip_log_1: "{{ hostvars['cus-utility-prod-log-1.cus.pm']['nic_wg_mesh_ip'] }}"
    # shorewall_util_wg_mesh_ip_git_1: "{{ hostvars['cus-utility-prod-git-1.cus.pm']['nic_wg_mesh_ip'] }}"
    # shorewall_util_wg_mesh_ip_gitci_1: "{{ hostvars['cus-utility-prod-gitci-1.cus.pm']['nic_wg_mesh_ip'] }}"

    # utility servers public IPs
    shorewall_util_pub_ip_gateway_1: 10.0.0.5
    shorewall_util_pub_ip_gateway_2: 10.0.0.6
    shorewall_util_pub_ip_backup_1: 10.0.0.7
    shorewall_util_pub_ip_monitoring_1: 10.0.0.8
    shorewall_util_pub_ip_log_1: 10.0.0.9
    shorewall_util_pub_ip_git_1: 10.0.0.10
    shorewall_util_pub_ip_gitci_1: 10.0.0.11
    # utility servers wireguard mesh IPs
    shorewall_util_wg_mesh_ip_gateway_1: 172.16.0.5
    shorewall_util_wg_mesh_ip_gateway_2: 172.16.0.6
    shorewall_util_wg_mesh_ip_backup_1: 172.16.0.7
    shorewall_util_wg_mesh_ip_monitoring_1: 172.16.0.8
    shorewall_util_wg_mesh_ip_log_1: 172.16.0.9
    shorewall_util_wg_mesh_ip_git_1: 172.16.0.10
    shorewall_util_wg_mesh_ip_gitci_1: 172.16.0.11

    # wireguard
    shorewall_nic_wireguard: wg0
    shorewall_nic_wireguard_net: 172.16.128.0/17

    # custom rules
    shorewall_rules_custom:
      - name: allow vagrant ssh
        src: pub
        dest: local
        proto: tcp
        dest_ports: 22,2200,2222
        action: ACCEPT
      - name: allow vagrant DNS to all
        src: local
        dest: pub
        action: DNS(ACCEPT)
    shorewall6_rules_custom:
      - name: allow vagrant DNS to all
        src: local
        dest: pub
        action: DNS(ACCEPT)

    # rules from templates
    shorewall_rule_templates:
      - utility_gateway
      - utility_monitoring
      - utility_log
      - utility_backup
      - utility_git
      - utility_git_pub
      - utility_gitci
      - git_client
      - inc_wg_mesh_http
      - inc_pub_http
      - inc_pub_ssh
      - out_pub_ssh

    # custom zones
    shorewall_zones_custom:
      - name: "wg"
        in_options: ""
        options: ""
        out_options: ""
        type: ipv4

    # custom interfaces
    shorewall_interfaces_custom:
      - name: wg0
        zone: wg
        options: tcpflags,nosmurfs,routefilter,logmartians
